export const episodesFilterNames = [
  "Pilot",
  "Lawnmower Dog",
  "Anatomy Park",
  "M. Night Shaym-Aliens!",
  "Meeseeks and Destroy",
  "Rick Potion #9",
  "Raising Gazorpazorp",
  "Rixty Minutes",
  "Something Ricked This Way Comes",
  "Close Rick-counters of the Rick Kind",
  "Ricksy Business",
  "A Rickle in Time",
  "Mortynight Run",
  "Auto Erotic Assimilation",
  "Total Rickall",
  "Get Schwifty",
  "The Ricks Must Be Crazy",
  "Big Trouble in Little Sanchez",
  "Interdimensional Cable 2: Tempting Fate",
  "Look Who's Purging Now",
];
